### ISSUE TITLE
Problem with the version 2.6's images

### ISSUE THREAD

**Issue by Sairei** [theBowja/genshin-db#100]
Hi !
There is a problem with the version 2.6's images you just add.

<details>
<summary><b>For the characters file : </b></summary>

- **Ayato**
  - icon (https://upload-os-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Ayato.png)
  - namegachaslice (https://res.cloudinary.com/genshin/image/upload/sprites/UI_Gacha_AvatarIcon_Ayato.png)
  - namesideicon (https://res.cloudinary.com/genshin/image/upload/sprites/UI_AvatarIcon_Side_Ayato.png)
  - sideicon (https://upload-os-bbs.mihoyo.com/game_record/genshin/character_side_icon/UI_AvatarIcon_Side_Ayato.png)

</details>

<details>
<summary><b>For the talents file : </b></summary>

- **Ayato**
  - combat2 (https://res.cloudinary.com/genshin/image/upload/sprites/Skill_S_Ayato_01.png)
  - combat3 (https://res.cloudinary.com/genshin/image/upload/sprites/Skill_E_Ayato_01_HD.png)
  - passive1 (https://res.cloudinary.com/genshin/image/upload/sprites/UI_Talent_S_Ayato_05.png)
  - passive2 (https://res.cloudinary.com/genshin/image/upload/sprites/UI_Talent_S_Ayato_06.png)
  - passive3 (https://res.cloudinary.com/genshin/image/upload/sprites/UI_Talent_S_Ayato_07.png)

</details>

<details>
<summary><b>For the constellations file : </b></summary>

- **Ayato**
  - constellation (https://res.cloudinary.com/genshin/image/upload/sprites/Eff_UI_Talent_Ayato.png)
  - c1 (https://upload-os-bbs.mihoyo.com/game_record/genshin/constellation_icon/UI_Talent_S_Ayato_01.png)
  - c2 (https://upload-os-bbs.mihoyo.com/game_record/genshin/constellation_icon/UI_Talent_S_Ayato_02.png)
  - c3 (https://upload-os-bbs.mihoyo.com/game_record/genshin/constellation_icon/UI_Talent_U_Ayato_02.png)
  - c4 (https://upload-os-bbs.mihoyo.com/game_record/genshin/constellation_icon/UI_Talent_S_Ayato_03.png)
  - c5 (https://upload-os-bbs.mihoyo.com/game_record/genshin/constellation_icon/UI_Talent_U_Ayato_01.png)
  - c6 (https://upload-os-bbs.mihoyo.com/game_record/genshin/constellation_icon/UI_Talent_S_Ayato_04.png)

</details>

<details>
<summary><b>For the animals file : </b></summary>

- **bluethunderweasel**
  - nameicon (https://res.cloudinary.com/genshin/image/upload/sprites/UI_AnimalIcon_Marten_05.png)
- **lucklightfly**
  - nameicon (https://res.cloudinary.com/genshin/image/upload/sprites/UI_AnimalIcon_Boltbug_Lightbug_01.png)

</details>

<details>
<summary><b>For the enemies file : </b></summary>

- **blackserpentknightwindcutter**
  - nameicon (https://res.cloudinary.com/genshin/image/upload/sprites/UI_MonsterIcon_Darkwraith_Strong_Wind.png)
- **ruinserpent**
  - nameicon (https://res.cloudinary.com/genshin/image/upload/sprites/UI_MonsterIcon_Nithhoggr_None.png)
- **floatinghydrofungus**
  - nameicon (https://res.cloudinary.com/genshin/image/upload/sprites/UI_MonsterIcon_Fungus_Un_Gamma_Water.png)

</details>

<details>
<summary><b>For the achievementgroups file : </b></summary>

- **challengerseriesv**
  - nameicon (https://res.cloudinary.com/genshin/image/upload/sprites/UI_AchievementIcon_B004_Part5.png)
- **chasmlighter**
  - nameicon (https://res.cloudinary.com/genshin/image/upload/sprites/UI_AchievementIcon_A011.png)

</details>

<details>
<summary><b>For the materials file : </b></summary>

- **fragrantseasoning**
  - nameicon (https://res.cloudinary.com/genshin/image/upload/sprites/UI_ItemIcon_101714.png)
- **fungalspores**
  - nameicon (https://res.cloudinary.com/genshin/image/upload/sprites/UI_ItemIcon_101714.png)
- **luminescentpollen**
  - nameicon (https://res.cloudinary.com/genshin/image/upload/sprites/UI_ItemIcon_112060.png)
- **crystallinecystdust**
  - nameicon (https://res.cloudinary.com/genshin/image/upload/sprites/UI_ItemIcon_112061.png)
- **runicfang**
  - nameicon (https://res.cloudinary.com/genshin/image/upload/sprites/UI_ItemIcon_113035.png)

</details>

<details>
<summary><b>For the foods file : </b></summary>

- **katsusandwich**
  - nameicon (https://res.cloudinary.com/genshin/image/upload/sprites/UI_ItemIcon_108382.png)
- **quietelegance**
  - nameicon (https://res.cloudinary.com/genshin/image/upload/sprites/UI_ItemIcon_108387.png)
- **rainbowaster**
  - nameicon (https://res.cloudinary.com/genshin/image/upload/sprites/UI_ItemIcon_108385.png)

</details>

<details>
<summary><b>For the artifacts file : </b></summary>

- **vermillionhereafter**
  - flower (https://upload-os-bbs.mihoyo.com/game_record/genshin/equip/UI_RelicIcon_15023_4.png)
  - plume (https://upload-os-bbs.mihoyo.com/game_record/genshin/equip/UI_RelicIcon_15023_2.png)
  - sands (https://upload-os-bbs.mihoyo.com/game_record/genshin/equip/UI_RelicIcon_15023_5.png)
  - goblet (https://upload-os-bbs.mihoyo.com/game_record/genshin/equip/UI_RelicIcon_15023_1.png)
  - circlet (https://upload-os-bbs.mihoyo.com/game_record/genshin/equip/UI_RelicIcon_15023_3.png)
- **echoesofanoffering**
  - flower (https://upload-os-bbs.mihoyo.com/game_record/genshin/equip/UI_RelicIcon_15024_4.png)
  - plume (https://upload-os-bbs.mihoyo.com/game_record/genshin/equip/UI_RelicIcon_15024_2.png)
  - sands (https://upload-os-bbs.mihoyo.com/game_record/genshin/equip/UI_RelicIcon_15024_5.png)
  - goblet (https://upload-os-bbs.mihoyo.com/game_record/genshin/equip/UI_RelicIcon_15024_1.png)
  - circlet (https://upload-os-bbs.mihoyo.com/game_record/genshin/equip/UI_RelicIcon_15024_3.png)

</details>

<details>
<summary><b>For the weapons file : </b></summary>

- **harangeppakufutsu**
  - namegacha (https://res.cloudinary.com/genshin/image/upload/sprites/UI_Gacha_EquipIcon_Sword_Amenoma.png)
  - icon (https://upload-os-bbs.mihoyo.com/game_record/genshin/equip/UI_EquipIcon_Sword_Amenoma.png)
  - nameawakenicon (https://res.cloudinary.com/genshin/image/upload/sprites/UI_EquipIcon_Sword_Amenoma_Awaken.png)
  - awakenicon (https://upload-os-bbs.mihoyo.com/game_record/genshin/equip/UI_EquipIcon_Sword_Amenoma_Awaken.png)

</details>

\
I don't know if it's normal or not, but I prefer to report it (just in case) :smiley: 

I have not tried the images of the new files (`geographies.json` and `namecards.json`)

**Comment by ahmadkeren** [comment]
Up

**Comment by theBowja** [comment]
I've uploaded the images to res.cloudinary now. Sorry for the wait.

Mihoyo still doesn't have images for theirs though but it shouldn't matter.

**Comment by ahmadkeren** [comment]
2 Artifact imgs is still not available

**Comment by theBowja** [comment]
unfortunately mihoyo hasn't uploaded their artifact images. you can use the res.cloudinary version instead.

err you'll have to extract the filename (UI_RelicIcon_15023_4) yourself. i fix that in a future update
