### ISSUE TITLE
Achivement and AchivementGroup

### ISSUE THREAD

**Issue by Sairei** [theBowja/genshin-db#103]
Hi !
I don't know if I'm doing something wrong, but I can't get the achievements and achievement goups.

With the lines below, I get an "undefined" in both variables :
```javascript
const genshindb = require('genshin-db');

let achivement = genshindb.achievements('name', { matchCategories: true });
let achivementGroup = genshindb.achievementgroups('name', { matchCategories: true });
```

Am I doing something wrong ?

**Comment by theBowja** [comment]
achievements and achievementgroups are not part of the main package because I was afraid that the size would get too big.

you'll have to look at https://github.com/theBowja/genshin-db/tree/main/dist

**Comment by Sairei** [comment]
Hmmm... Now with this line (and only it)
```javascript
let achivementGroup = genshindb.achievementgroups('name', { matchCategories: true });
```
I have this error : 
```log
Uncaught TypeError: langindex.categories is undefined
    retrieveData main.js:107
    achievementgroup main.js:332
    ...
```


I think I find solution :\
In the `main.js` file at line 107, I think we need to change the condition 
```javascript
if (opts.matchCategories && (langindex.categories[queryMatch] !== undefined || queryMatch === 'names')) {
[...]
}
```
by
```javascript
if (opts.matchCategories && (queryMatch === 'names' || langindex.categories[queryMatch] !== undefined)) {
[...]
}
```
It does not change the condition, but it allows the achivementgroups to pass since there are no categories

**Comment by theBowja** [comment]
that's really weird... could you tell me which data file you've downloaded and what options you set genshindb to?

**Comment by theBowja** [comment]
oh nvm. looks like it was a problem with importing data. it failed to import categories as {}.

**Comment by theBowja** [comment]
v4.2.0
`npm install genshin-db@latest`
