### ISSUE TITLE
add a feature to change to typescript types or use more specific typings?

### ISSUE THREAD

**Issue by oniiichannnn** [theBowja/genshin-db#105]
my interface is like
```ts
interface character {
 ...
 rarity: "4"|"5"
}
```
where in ur typing it is 
```ts
rarity: string
```

**Comment by theBowja** [comment]
thanks. i'll fix this

**Comment by theBowja** [comment]
changed in commit e7d2551313df43c6f0d5f1e83bdd99eea54f9f71
package will probably be released end of this month
