### ISSUE TITLE
Whether to consider adding beta data

### ISSUE THREAD

**Issue by 1011382654** [theBowja/genshin-db#111]

**Comment by 1011382654** [comment]
> 



> as far as I know, it's not possible at all. You can check the dimbreath repository. https://github.com/Dimbreath/GenshinData
> 
> and this repository is updated only when a new update is available. Also this is the main data source for the info.

https://ambr.top This kind of website seems to be provided. Is it reliable?

**Comment by theBowja** [comment]
I only extract data from Dimbreath's data dump. Dimbreath does not include beta data in his data dump. I will not include beta data in my repo.

My npm package has a way to import data yourself however there is little to no documentation on it. It is on my radar to make this easier to do.
