### ISSUE TITLE
item with same name

### ISSUE THREAD

**Issue by Sairei** [theBowja/genshin-db#114]
Hi,

I noticed that there are objects with the same name, but which are different, such as "Key Sigil" materials or "Prized Isshin Blade" weapons. 
How can I do to retrieve information from different objects ?

**Comment by theBowja** [comment]
hmm I'm not sure how to fix this

**Comment by theBowja** [comment]
Can now search for data with the same name by adding a number. Indexed at 0. Must set matchAliases to true.

Example: genshindb.achievements('Let the wind lead 1', { matchAliases: true })

v4.3.1
