### ISSUE TITLE
Support wildcards for getting all of X

### ISSUE THREAD

**Issue by Primajin** [theBowja/genshin-db#115]
Hey there, I can see many requests for getting 'all' of X.
I would like to be able to call either `genshindb.foods()` or `genshindb.foods('')` or `genshindb.foods('*')` to just get all foods.

Currently what I do is I loop through the category first
```js
const aggregator = [];
for (let i = 1; i < 6; i++) {
  aggregator.push(genshinDB.foods(i, {matchCategories: true}));
}
```
and then map through the foods again
```js
aggregator.map(category => category.map(itemName => genshinDB.foods(itemName)));
```

Would be really helpful if we could just get all!

**Comment by theBowja** [comment]
Does
`genshindb.foods('names', { matchCategories: true, verboseCategories: true })`
match what you're looking for?

**Comment by Primajin** [comment]
Ohh yes perfect! Thank you!

**Comment by theBowja** [comment]
Looks like I need to add this somewhere to my docs since I get asked this the most.

**Comment by Primajin** [comment]
I am currently gathering a couple of questions - I'm happy to post them here later.

There are some things that are a bit unclear from the docs or are not up to date any more (e.g. links pointing to 404) etc.
