### ISSUE TITLE
typings error

### ISSUE THREAD

**Issue by oniiichannnn** [theBowja/genshin-db#127]
Im using typescript and when i import the module it gives an error saying it cannot find the types for the module

i looked at the module folder and found that u put the `index.d.ts` file inside a typings folder instead of the root folder. i move the `index.d.ts` file to the root folder
![image](https://user-images.githubusercontent.com/67128188/202753319-835b0a69-65c3-4ac1-b75b-c3c8932fdb87.png)
and my error is gone and now i just need to change the paths inside the typings

**Comment by theBowja** [comment]
my package json file has   "types": "./types/index.d.ts",
so you should have been able to find the the types at that location?
