### ISSUE TITLE
What is the latest url for using nameIcons and such images. This url doesnt seem to work

### ISSUE THREAD

**Issue by VasuGarg07** [theBowja/genshin-db#129]
[v3.10.3](https://github.com/theBowja/genshin-db/releases/tag/v3.10.3)

You can access gacha splash images by doing:
```
let imagename = genshindb.characters("hu tao").images.namegachasplash; // UI_Gacha_AvatarImg_Hutao
let url = `https://res.cloudinary.com/genshin/image/upload/2.1/${imagename}.png`;
```
---------------------------

all UI images zip download https://www.mediafire.com/file/l1xw41d0kndsh7k/images2.1.7z/file (1GB)

cloud hosted with 25GB monthly bandwidth https://res.cloudinary.com/genshin/image/upload/2.1/UI_AvatarIcon_Diona_Card.png (just change the file name at the end)

_Originally posted by @theBowja in https://github.com/theBowja/genshin-db/issues/45#issuecomment-921491545_

**Comment by theBowja** [comment]
Url changed sorry
all images are accessed from `https://res.cloudinary.com/genshin/image/upload/sprites/${filename}.png`
