### ISSUE TITLE
Is it available to add Genius Invokation TCG card to database? 

### ISSUE THREAD

**Issue by Frully** [theBowja/genshin-db#131]
Hi,
Is it available to add Genius Invokation TCG card to database?

**Comment by theBowja** [comment]
im working on it. it'll probably take a while

**Comment by theBowja** [comment]
data has been uploaded to the repo. 16442d4022f60806dfec260dc6ea11d4f95b807d
I will make a new package update tomorrow.
There's still a lot missing. If there's any data you would like added, please make a github issue or ask me in my discord.

**Comment by Frully** [comment]
Many thanks to @theBowja for such excellent work.
I found that the images of the cards are not included in the data, will it be added in the future?

**Comment by theBowja** [comment]
just added images 82b5487e26cb022f30175b2f1861bec4c09fbc6a

**Comment by theBowja** [comment]
Added with `@genshin-db/tcg` latest release v4.3.5.
`npm install @genshin-db/tcg@latest`
