### ISSUE TITLE
Geographies not found

### ISSUE THREAD

**Issue by VasuGarg07** [theBowja/genshin-db#134]
Using latest version of the package in typescript. having error accessing geographies.

`Property 'geographies' does not exist on type 'typeof import("genshin-db")'.`

I checked the Index file and ...
![Screenshot 2022-12-29 114341](https://user-images.githubusercontent.com/43118352/209911094-94d202e2-486a-42d6-b230-a14e59b9679a.png)

I guess it was simply missed?

**Comment by theBowja** [comment]
Oh whoops

**Comment by theBowja** [comment]
Fixed in latest release 4.3.5.
`npm install genshin-db@latest`
