### ISSUE TITLE
What's these curves ?

### ISSUE THREAD

**Issue by AkihiroEmiya** [theBowja/genshin-db#137]
Hello !

I didn't know how to contact you, so I'll ask the question here.

I would just know what's exactly all the curves in the ``all.curve`` in the file ``./src/getdata.js``

Also what represent the ``key``, I thought it was the level or the character/weapon but I see that it goes to 100 but the levels stop at 90.
Can you please enlighten me about this? =D

**Comment by theBowja** [comment]
https://github.com/theBowja/genshin-db/blob/main/src/data/curve/characters.json

The curves are used to calculate the stats for a character/weapon at a certain level. In the files, there are calculations for up to level 100 but currently there is no way to get higher than level 90 in the game.

In my `getdata.js`, my calculations are in the `calcStatsCharacter` function and etc. https://github.com/theBowja/genshin-db/blob/main/src/getdata.js#L136

If you would like a standalone script for calculating stats, you can find it here at https://github.com/theBowja/GenshinData-scripts/tree/main/stats.

Let me know if you need clarification on anything.

**Comment by AkihiroEmiya** [comment]
Thanks for the standalone script ! This is indeed one of the things I was looking for.

In fact I tried to found the baseAtk formula for weapons but I failed. And know I'm seeing your curves that seems very accurate. I was wondering how did you find them ?

Also, if we take a curve alone : 
```js
      GROW_CURVE_ATTACK_101: 2.4200000762939453,
      GROW_CURVE_ATTACK_102: 2.556999921798706,
      GROW_CURVE_ATTACK_103: 2.686000108718872,
      GROW_CURVE_ATTACK_104: 2.2750000953674316,
      GROW_CURVE_ATTACK_105: 2.121000051498413,
      GROW_CURVE_CRITICAL_101: 1.7669999599456787,
      GROW_CURVE_ATTACK_201: 2.569000005722046,
      GROW_CURVE_ATTACK_202: 2.7109999656677246,
      GROW_CURVE_ATTACK_203: 2.8450000286102295,
      GROW_CURVE_ATTACK_204: 2.4170000553131104,
      GROW_CURVE_ATTACK_205: 2.25600004196167,
      GROW_CURVE_CRITICAL_201: 1.7669999599456787,
      GROW_CURVE_ATTACK_301: 2.6500000953674316,
      GROW_CURVE_ATTACK_302: 2.803999900817871,
      GROW_CURVE_ATTACK_303: 2.9489998817443848,
      GROW_CURVE_ATTACK_304: 2.484999895095825,
      GROW_CURVE_ATTACK_305: 2.306999921798706,
      GROW_CURVE_CRITICAL_301: 1.7669999599456787
    },
```

What represent all these curves. Is it something like 
``GROW_CURVE_ATTACK_10X`` => Curves for 3 stars weapons
``GROW_CURVE_ATTACK_20X`` => Curves for 4 stars weapons
``GROW_CURVE_ATTACK_30X`` => Curves for 5 stars weapons

And if yes what's ``GROW_CURVE_CRITICAL_X01`` ??

I'm sorry if this goes into too much detail, if you insist on not answering, I would understand !

**Comment by theBowja** [comment]
Those numbers are extracted straight from the game files. You can find the stats I've extracted here: https://github.com/theBowja/genshin-db/blob/main/src/data/stats/weapons.json

**Comment by AkihiroEmiya** [comment]
Owh well, so there was no formula ? Nooo I spent 2 days searching xD
Aight ! Thank you so much ! You're really a genius !

**Comment by theBowja** [comment]
Yeah I had to figure out all the calculations and find the data myself. Good luck with whatever you're trying to do.
