### ISSUE TITLE
Sumeru Talent Mats - Material Type typo

### ISSUE THREAD

**Issue by Zerodymegx** [theBowja/genshin-db#141]
Hey there. 

The Sumeru Talent Level up material's Material type is "Talent Level-Up Materials". 
All other Talent level up materials has Material type : "Talent Level-Up Material"

The differernce is there is an extra 's' for the Sumeru ones. 
The issue is that because of this you can't find Sumeru materials when you query "talent" or "talent Level". 

So something like genshinDb.materials("talent level", {"matchAliases":true,"matchCategories":true}); results in: 

[
"Crown of Insight",
"Guide to Ballad",
"Guide to Diligence",
"Guide to Elegance",
"Guide to Freedom",
"Guide to Gold",
"Guide to Light",
"Guide to Prosperity",
"Guide to Resistance",
"Guide to Transience",
"Philosophies of Ballad",
"Philosophies of Diligence",
"Philosophies of Elegance",
"Philosophies of Freedom",
"Philosophies of Gold",
"Philosophies of Light",
"Philosophies of Prosperity",
"Philosophies of Resistance",
"Philosophies of Transience",
"Teachings of Ballad",
"Teachings of Diligence",
"Teachings of Elegance",
"Teachings of Freedom",
"Teachings of Gold",
"Teachings of Light",
"Teachings of Prosperity",
"Teachings of Resistance",
"Teachings of Transience"
]

You can't actually find Sumeru material unless you specifically query for "materials". 

Anyways would you be able to make this material type consistent? 
Also slightly unrelated note, the Version info is missing for most of the  materials. Are you planning to add them in near future?

**Comment by theBowja** [comment]
Hi, there's no typo. Those strings are exactly the same as they are in-game. Unfortunately the in-game translations aren't perfect and contain a difference in a single letter. I'm not willing to fix this specifically. I'm probably gonna remove the category search for the translated material types. Then add in some enum type later that doesn't depend on strings that have potential mistranslations.

I don't think I'll be updating material versions any time soon. I plan to eventually but I'm busy with other issues. Updating material versions will be manual work and it just needs to change the `data/versions/materials.json` file if anyone wants to volunteer.

Apologies.

**Comment by Zerodymegx** [comment]
Hey again. 
I see. Is it possible for query for to get results for multiple types with similar names? That would be more convinient.
Like an aggregate, so that a query for "material" will give us query results both "material" and "materials". 
I assumed that disbaling matching names should work out but it didn't. 

Will that break something else intended to work ?

**Comment by theBowja** [comment]
You can do two separate queries for "material" and "materials" then join the results yourself.
