### ISSUE TITLE
Image link cannot be accessed

### ISSUE THREAD

**Issue by 1011382654** [theBowja/genshin-db#148]
![image](https://github.com/theBowja/genshin-db/assets/26688758/ff936303-b207-4b8a-b812-524af16f17fe)

**Comment by jsdawn** [comment]
https://res.cloudinary.com/genshin/image/upload/sprites/UI_AvatarIcon_Xiao.png
This is also lost！

**Comment by theBowja** [comment]
@jsdawn link works for me

**Comment by theBowja** [comment]
@jsdawn turns out i hit the bandwidth limit for my image host

**Comment by theBowja** [comment]
and also my account got disabled lol

**Comment by Leadstoyou** [comment]
> and also my account got disabled lol so rip my image host

:(((((

**Comment by theBowja** [comment]
got my account enabled again
