### ISSUE TITLE
Lightless Mass data no exist

### ISSUE THREAD

**Issue by ahmadkeren** [theBowja/genshin-db#154]
Lightless Mass data monster not exist..

**Comment by ahmadkeren** [comment]
let data = await genshindb.enemies('Lightless Mass')
console.log(data)
return null

**Comment by theBowja** [comment]
Is that a mob? It's not in the in-game archive

**Comment by ahmadkeren** [comment]
> Is that a mob? It's not in the in-game archive

yes, for furina and charlotte talent materials

**Comment by ahmadkeren** [comment]
sorry, iam wrong.. that boss is "All-Devouring Narwhal"

**Comment by ahmadkeren** [comment]
let data = await genshindb.materials('Lightless Mass')
the sources is blank..

**Comment by ahmadkeren** [comment]
![Screenshot at Nov 08 11-17-57](https://github.com/theBowja/genshin-db/assets/49072140/fd9c2933-d235-4f54-99a8-3f2d74cbebe3)

**Comment by theBowja** [comment]
Oh yeah I think something messed up with sources... Hmm. I'll be back home Friday so I can only look into it over the weekend.

**Comment by ahmadkeren** [comment]
> Oh yeah I think something messed up with sources... Hmm. I'll be back home Friday so I can only look into it over the weekend.
enjoy your time. Oh yes, I found something else that was left behind, namely "images name/filenameicon" from the constellations Furina and Charlotte

let check = await genshindb.constellations(q);
// result: images = {}

**Comment by theBowja** [comment]
oh. thanks for the catch. i messed up my extractor for constellation image

**Comment by ahmadkeren** [comment]
> Oh yeah I think something messed up with sources... Hmm. I'll be back home Friday so I can only look into it over the weekend.

still faithfully waiting while eating almond tofu 😊

**Comment by ahmadkeren** [comment]
> oh. thanks for the catch. i messed up my extractor for constellation image

any function to put additional information for that modul?
i want to add constelation image and source materials

**Comment by ahmadkeren** [comment]
I put manually into the .json

**Comment by theBowja** [comment]
I'm gonna put out an update tonight. Sorry for delay
