### ISSUE TITLE
New Weekly Boss Rewards List return Blank Array

### ISSUE THREAD

**Issue by ahmadkeren** [theBowja/genshin-db#155]
![image](https://github.com/theBowja/genshin-db/assets/49072140/aeeb79cc-d22c-4ab4-894e-9f795739ace2)

**Comment by theBowja** [comment]
my bad. i got lazy here

**Comment by theBowja** [comment]
i'll put out an update over the weekend. or next week. or next month... idk

no reward list for 22020201 : Abyss Herald: Frost Fall
no reward list for 22100501 : Iniquitous Baptist
no reward list for 22080201 : Black Serpent Knight: Rockbreaker Ax
no reward list for 24068101 : Recon Log Mek
no reward list for 24068201 : Arithmetic Enhancer Mek
no reward list for 24068301 : Underwater Survey Mek
no reward list for 24068501 : Underwater Patrol Mek
no reward list for 24068601 : Deepwater Assault Mek
no reward list for 24068701 : Nimble Harvester Mek
no reward list for 24069101 : Area Alert Mek
no reward list for 24068801 : Assault Specialist Mek
no reward list for 24068901 : Suppression Specialist Mek
no reward list for 24069001 : Annihilation Specialist Mek
no reward list for 24069201 : Construction Specialist Mek
no reward list for 24070301 : Icewind Suite
no reward list for 25410301 : Eremite Scorching Loremaster
no reward list for 25410401 : Eremite Floral Ring-Dancer
no reward list for 26100101 : Consecrated Horned Crocodile
no reward list for 26100201 : Consecrated Fanged Beast

**Comment by theBowja** [comment]
fixed in latest db v5

**Comment by ahmadkeren** [comment]
> fixed in latest db v5

thank you so much
