### ISSUE TITLE
Excited for 4.3 data

### ISSUE THREAD

**Issue by ahmadkeren** [theBowja/genshin-db#157]
Enjoy your time. I'm waiting for genshin maintenance to finish (+- 2 hours in the gmt+7 time zone) so I wrote this ^_^

**Comment by theBowja** [comment]
oh i didnt know update was tonight. i'll get around to it in a day or two...

**Comment by ahmadkeren** [comment]
> oh i didnt know update was tonight. i'll get around to it in a day or two...

Thank you, I'm still patiently waiting ^_^

**Comment by theBowja** [comment]
updated v5 genshin-db

**Comment by ahmadkeren** [comment]
> updated v5 genshin-db

thank you sir
