### ISSUE TITLE
v4.3 TCG summons/statusEffects are missing in other languages

### ISSUE THREAD

**Issue by Guyutongxue** [theBowja/genshin-db#159]
For example, id `112091` (Yelan's status effect) can only be found in English in `@genshin-db/tcg/src/data.min.json`. 

In commit 3ee66eff, you can see only English's TCG index is fully updated, while other lanuguages only have `tcgactioncards` and `tcgcharactercards` updated.

**Comment by theBowja** [comment]
Ah. I had switched to English-only because I was fixing a bug with tcg extractor, but then I forgot to undo it. @.@

**Comment by Guyutongxue** [comment]
Fixed in v5.0.5, thank you!
