### ISSUE TITLE
v4.3 "non-acquirable" TCG character-cards

### ISSUE THREAD

**Issue by Guyutongxue** [theBowja/genshin-db#160]
4.3 TCG adds 5 character-cards that can only be obtained by "switching" from another character cards. They are:
- id `6301` **Crimson Witch of Embers**, switched from `2102` **La Signora**;
- id `6601` **Azhdaha** (Absorbed cryo), switched from `2602` **Azhdaha**;
- id `6602` **Azhdaha** (Absorbed hydro);
- id `6603` **Azhdaha** (Absorbed pyro);
- id `6604` **Azhdaha** (Absorbed electro).

They are presented in original GenshinData `GCGCharExcelConfigData.json`. But they can't be extracted... maybe the problem is here:

https://github.com/theBowja/GenshinData-scripts/blob/c1852ce02e7c4465dbbebf9c5346a5753e8b75e4/extract/extractTcgCharacterCard.js#L38-L39

...because these 5 characters are neither "playable" nor "enemy", so they will always be ignored. Any idea to solve this?

**Comment by theBowja** [comment]
Ooh I knew I missed something with the new tcg cards. I'll go try them out before coming up with something. Might do something like add properties "transformTo" or "transformedFrom".

**Comment by theBowja** [comment]
published. new properties transformsinto and istransformation

https://github.com/theBowja/GenshinData-scripts/commit/56e429d7d71a2b445ccb0546e6eb289045bdbb97
it took a bit of effort o.o

**Comment by Guyutongxue** [comment]
Wow, amazing! Thanks👍
