### ISSUE TITLE
[Feature Request] Add TCG cards "sharing code" id

### ISSUE THREAD

**Issue by Guyutongxue** [theBowja/genshin-db#162]
This property defined at `ExcelBinOutput/GCGDeckCardExcelConfigData.json`
![image](https://github.com/theBowja/genshin-db/assets/33127223/e835b9b7-71da-4005-92de-44c5856051cf)
... counting from 1 to 318 (v4.3 now) which is useful when generating card deck sharing code. Detailed TCG sharing code algorithm can be found in [this repo](https://github.com/gjfLeo/summoners-summit/blob/main/utils/decks/share-code.ts) (and also [here](https://github.com/isHarryh/GI-Code-Converter), a Python file just decode to "1~318" number list).

It will be great to include this in every character cards and action cards. By the way, my suggestion of naming this property might be `encodingid` `sharingcodeid` or `orderid` or something else... I'm not sure :(

**Comment by theBowja** [comment]
oh interesting. I'll have to look into this

**Comment by Guyutongxue** [comment]
Thank you!
