### ISSUE TITLE
Waiting 4.4 Data

### ISSUE THREAD

**Issue by ahmadkeren** [theBowja/genshin-db#164]
finally we can gacha xianyun, we are still waiting to get 4.4. enjoy your time friend :)

**Comment by theBowja** [comment]
i'll get it done tonight. some problems with tcg again xdd

**Comment by theBowja** [comment]
https://github.com/theBowja/genshin-db/releases/tag/v5.0.9

**Comment by ahmadkeren** [comment]
> https://github.com/theBowja/genshin-db/releases/tag/v5.0.9

thank you sir
