### ISSUE TITLE
Miss Emperor of Fire and Iron Boss?

### ISSUE THREAD

**Issue by ahmadkeren** [theBowja/genshin-db#165]
It seems there is an error in the boss data "Emperor of Fire and Iron", in genshin-db the monster is considered a normal monster

**Comment by theBowja** [comment]
![image](https://github.com/theBowja/genshin-db/assets/12958524/def3742f-9f74-4a87-9daf-8800cc65b975)
ermmmmmmmmmmmm

**Comment by theBowja** [comment]
looks like something in my extractor is mixing up the boss crab with the mob crab xdd

**Comment by ahmadkeren** [comment]
> looks like something in my extractor is mixing up the boss crab with the mob crab xdd

XD

**Comment by theBowja** [comment]
published under genshin-db@5.1.0

**Comment by ahmadkeren** [comment]
> published under genshin-db@5.1.0

thanks sir
