### ISSUE TITLE
@genshin-db/tcg is not a module

### ISSUE THREAD

**Issue by gjfLeo** [theBowja/genshin-db#166]
```typescript
import genshindbtcg from "@genshin-db/tcg";
```
Then I got "....../node_modules/@genshin-db/tcg/types/index.d.ts is not a module." 
But `genshindbtcg.tcgcharactercards` works well (without type hint though).
Maybe some type definition missing?

**Comment by gjfLeo** [comment]
The `.d.ts` files in `@genshin-db/tcg` now declare `genshin-db` (`@genshin-db/tcg` expected).

**Comment by theBowja** [comment]
fixed. sorry for delay. was working on something else. thanks
