### ISSUE TITLE
Missing filename_icon at chiori data

### ISSUE THREAD

**Issue by ahmadkeren** [theBowja/genshin-db#167]
chiori data
![image](https://github.com/theBowja/genshin-db/assets/49072140/680d7141-7603-4b2e-aa6c-c632c1d62910)

diluc data
![image](https://github.com/theBowja/genshin-db/assets/49072140/d183683b-68d3-41fa-b15d-4700744f235b)

**Comment by theBowja** [comment]
🤦

**Comment by theBowja** [comment]
fixed. `npm install genshin-db@latest`
v5.1.3

**Comment by ahmadkeren** [comment]
> fixed. `npm install genshin-db@latest` v5.1.3

thanks sir
