### ISSUE TITLE
[OOT] Wuthering Waves Modul

### ISSUE THREAD

**Issue by ahmadkeren** [theBowja/genshin-db#168]
Thank you in advance, if so, we would like to request a module like Genshin-DB for the Wuthering Waves game. I see this game has good potential.

**Comment by theBowja** [comment]
I tried the game for a few hours. Not too impressed. Don't think I'll stick with it for long. So there won't be a module for Wuthering Waves. Sorry.

**Comment by theBowja** [comment]
You can grab the data yourself from the datadump. https://github.com/Dimbreath/WutheringData
