### ISSUE TITLE
Bugs of TCG `D__KEY__DAMAGE` replacement

### ISSUE THREAD

**Issue by guyutongxue** [theBowja/genshin-db#169]
In the latest version, `D__KEY__DAMAGE` may be replaced incorrectly when `D__KEY__DAMAGE_\d` is presented.

Example: Tartaglia's skill 12043

> `Performs different attacks based on the current stance that <color=#FFFFFFFF>$[A1204]</color> is in.\\n<color=#FFFFFFFF>Ranged Stance - Flash of Havoc: </color>Deal $[D__KEY__DAMAGE_5] $[D__KEY__ELEMENT], reclaim 2 \$[K310], and apply <color=#FFFFFFFF>$[C112043]</color> to the target character.\\n<color=#FFFFFFFF>Melee Stance - Light of Obliteration</color>: Deal $[D__KEY__DAMAGE] $[D__KEY__ELEMENT].`

Notice that `basedamage` of this skill is 7, but the replaced text is:

> Performs different attacks based on the current stance that Tartaglia is in.  
> Ranged Stance - Flash of Havoc: Deal 5 Hydro DMG, reclaim 2 Energy, and apply Riptide to the target character.  
> Melee Stance - Light of Obliteration: Deal **5** Hydro DMG.

**Comment by theBowja** [comment]
thanks. i knew something looked kinda weird with tartaglia but didnt have time to look closely
