### ISSUE TITLE
Artifacts

### ISSUE THREAD

**Issue by Varmolord** [theBowja/genshin-db#17]
Hi! 
Could you make something to find the artifacts for the character by his name?
For example: 
**genshin.artifacts(`Diluc`)**

BTW: In the examples of artifacts you're writing **genshin.artifacts('flame')**, and my second question is where I can get the 'flame'? I didn't found it even in character or inside of his elements.

**Comment by theBowja** [comment]
Artifacts aren't tied to any characters specifically. I can put Noblesse Oblige or whatever on Diluc if I want so it makes no sense to add a search for artifacts by character name. If you really want this "suggested artifact" feature, then you'll have to make a fork and add it yourself. I can help you with it there.

'flame' is part of the artifact set name of 'Crimson Witch of Flames'. So if you search genshin.artifacts('flame') it'll return the information for that artifact set.

**Comment by Varmolord** [comment]
> Artifacts aren't tied to any characters specifically. I can put Noblesse Oblige or whatever on Diluc if I want so it makes no sense to add a search for artifacts by character name. If you really want this "suggested artifact" feature, then you'll have to make a fork and add it yourself. I can help you with it there.
> 
> 'flame' is part of the artifact set name of 'Crimson Witch of Flames'. So if you search genshin.artifacts('flame') it'll return the information for that artifact set.

Ok, thank you. I'll try it by myself, just find out that if you type **genshin.artifacts('Mona')** it works.

**Comment by theBowja** [comment]
I use autocomplete to help with searches. "Mona" will match 'Cri**m**s**on** Witch of Fl**a**mes'.

Btw I have no plans to add 'suggested' artifact to my library.
