### ISSUE TITLE
TCG character skills wrong `D__KEY__DAMAGE_n` replacement

### ISSUE THREAD

**Issue by guyutongxue** [theBowja/genshin-db#171]
`D__KEY__DAMAGE_2` should not be replaced to `2` directly. In `Alldevouring Narwhal`'s elemental skill `22042`, `D__KEY__DAMAGE_2` is 1; in `Guardian of Apep's Oasis`'s elemental burst `27023`, `D__KEY__DAMAGE_2` is 4.

`D__KEY__DAMAGE_2` is something that needs to be looked up inside `BinOutput` just like what `D__KEY__DAMAGE` or `D__KEY__ELEMENT` does. FYI, the "hash" of `D__KEY__DAMAGE_2` is `1428448537` (found at `Char_Skill_22042.json` `Char_Skill_27023.json`).

**Comment by theBowja** [comment]
fixed (hopefully)

thanks!
