### ISSUE TITLE
Image for Childe not available

### ISSUE THREAD

**Issue by Ephrem-Adugna** [theBowja/genshin-db#23]
The `image.image` for `genshin.characters('childe', { matchAliases: true })` returns an invalid link.

**Comment by theBowja** [comment]
Thanks. I'll fix that next week with the 1.5 update.

In the meantime, I recommend using images.icon which is more reliable since it's from hoyolab.

**Comment by Ephrem-Adugna** [comment]
Ok, thanks

**Comment by theBowja** [comment]
version 3.2.0 of this library is out
