### ISSUE TITLE
Wrong letter in word

### ISSUE THREAD

**Issue by Marik-Db** [theBowja/genshin-db#25]
Hello,
today i looked through the files and noticed a mistake,
In the fille
genshin-db/src/data/German/talents/zhongli.json in "combat3" in "info" there is the word "\n**Versteingert**",
the g does not belong there.
I hope i could help.

**Comment by theBowja** [comment]
Interesting. Can you check if the typo is in the game as well? The data file I got it from has the g. If so, then I recommend submitting a report to genshin impact customer service.

I can make a minor patch for genshin-db too.

**Comment by Marik-Db** [comment]
Sorry that i could not respond earlier, i was busy with work.
Yes the typo is in the game as well, i am gonna submit that to the genshin impact customer service.
Will you change that in your files by yourself or are you just gonna copy the files again once its fixed?

**Comment by theBowja** [comment]
patched it myself. will publish a new npm version a bit.
