### ISSUE TITLE
inconsistent styling of decimals

### ISSUE THREAD

**Issue by AzureHakua** [theBowja/genshin-db#3]
numbers with decimals are inconsistent: they will either use periods or commas

examples:

- skyward harp substat (4.8%), lost prayer (7.2%) -> uses periods

- otherworldly story (8,5%), thrilling tales of dragon slayers (7,7%) -> uses commas

personal suggestion: use only periods (most english speaking countries like the us, uk, canada, and australia use periods, but also china, japan, and korea, the other major languages of genshin use periods)

**Comment by theBowja** [comment]
Fixed. I took these weapon data from someone else. I planning on separating the substat into two different properties but there's so many weapons and I'm lazy.
