### ISSUE TITLE
recipes not more available?

### ISSUE THREAD

**Issue by mpetrushin76** [theBowja/genshin-db#30]
I saw that the images of the recipes are available, and support for the "recipes" function was added in the commit on November 29 2020, but at the moment it is not. Images do not come in the "foods" function either.

**Comment by theBowja** [comment]
recipes function was removed in [version v3.2.0](https://github.com/theBowja/genshin-db/releases/tag/v3.2.0) and replaced by the foods function.

I will see if I can add back images in the next update.

**Comment by mpetrushin76** [comment]
Ok, thx
