### ISSUE TITLE
Unable to get the artifact set-bonuses data.

### ISSUE THREAD

**Issue by Another-19** [theBowja/genshin-db#31]
```{
	"name": "any artifact name here",
	"rarity": [
		"1",
		"2",
		"3"
	],
	"2pc": "Max HP increased by 1000.",
	"4pc": "Opening a chest regenerates 30% Max HP over 5s.",
	... and more stuff below etc.
```

`<genshin-db>.artifacts('any artifact name here').2pc` and `.4pc` will return **SyntaxError: Invalid or unexpected token**

Variable Error: You can NOT set variable name that has number/integer at their first letter.
Can you maybe by replacing `2pc` and `4pc` to something like `two-bonus` and `fullset-bonus`, or would you like me to fix the data for you by contributing?

**Comment by theBowja** [comment]
You can access the .2pc/4pc property using bracket notation.

For example artifact["2pc"].

I will consider changing the property name in the future.

**Comment by Another-19** [comment]
Oh, i didnt know that exists. Alright you made by day. Much thanks.
