### ISSUE TITLE
TS typings missing in npm package

### ISSUE THREAD

**Issue by daftcoder** [theBowja/genshin-db#32]
`index.d.ts` is missing after package installation

**Comment by daftcoder** [comment]
Maybe adding it in `files` section of `package.json` will fix that

**Comment by daftcoder** [comment]
Created pull request with the fix:
https://github.com/theBowja/genshin-db/pull/33

Please release new version of package to npm after merging. Thanks!

**Comment by theBowja** [comment]
oh wow thanks
