### ISSUE TITLE
add your own aliases

### ISSUE THREAD

**Issue by theBowja** [theBowja/genshin-db#37]
Add a way to register new aliases to data.

For example if I wanted the query 'Harem King' to return Aether character data.

```genshindb('Harem King', { matchAliases: true });```

**Comment by NepPure** [comment]
Is this feature still under development?

**Comment by theBowja** [comment]
I have not started on this yet. But I do plan on adding it eventually.

**Comment by NepPure** [comment]
Thanks for answering.

https://github.com/theBowja/genshin-db/blob/c4faa909f506b7d556a20c3795c593d118551a4f/src/data/image/characters.json#L10-L19

Are these image resources maintained manually? For example, "cover1", I haven't seen it in the game.

**Comment by theBowja** [comment]
I mainly manually update the links.

image, card, and portrait are wikia image links and I no longer update them. They can be considered deprecated or unreliable until I can figure out a way to automatically grab them from the wikia.

icon and sideicon property will always have links generated but availability of the images depend on hoyolab. Generally they have these images for new characters soon after they are live.

cover1 and cover2 I have a script that grabs them straight from the official website. https://genshin.mihoyo.com/en/character/mondstadt?char=0

hoyolab-avatar I grab them from hoyolab's profile icon list. Not every character will have this.

**Comment by theBowja** [comment]
If you know any image hosters that are reliable and easy to access, please let me know and I might add them.

**Comment by NepPure** [comment]
Thank you very much! Does the item icon come directly from the game unpacking data?

**Comment by theBowja** [comment]
"UI_AvatarIcon_Albedo" and "UI_AvatarIcon_Side_Albedo" comes straight from the game unpacking data.

**Comment by NepPure** [comment]
The data is very easy to use, I tried to make this. https://github.com/NepPure/genshin-card

![image](https://user-images.githubusercontent.com/12379907/132447671-a8e25442-a3d6-4d9f-abfd-650ca7f86400.png)

GitHub Pages:

https://genshin-card.neptunia.vip/cards/views/character.html?name=%E9%9B%B7%E7%94%B5%E5%B0%86%E5%86%9B

One problem is that no weapon images similar to "cover1" have been found. 

I seem to have seen them somewhere, but I forgot. I wonder if you have any impression.

Thank you very much again!

**Comment by theBowja** [comment]
Wow that looks really awesome. The images might load kinda slow. I recommend downscaling them or find a CDN that can automatically transform them from url or whatever.

All the weapon images similar to "cover1" are called `UI_Gacha_EquipIcon_${imagename}`

I've dumped every image and put [them on mediafire](https://www.mediafire.com/file/l1xw41d0kndsh7k/images2.1.7z/file). It's 1GB download.

Alternatively you can access them like: https://res.cloudinary.com/genshin/image/upload/2.1/UI_Gacha_EquipIcon_Claymore_Lapis.png

I haven't linked the urls in my database yet. You can still map the file names in my database yourself tho:

```
let dbimages= genshindb.weapons("Lost Prayers").images;
let imagename = dbimages.icon.slice(dbimages.icon.indexOf("UI_EquipIcon")+13); //grabs "Catalyst_Fourwinds.png"
console.log(`https://res.cloudinary.com/genshin/image/upload/2.1/UI_Gacha_EquipIcon_${imagename}`);
```

I only managed to find these images recently. There's still a lot of work to do to add them to genshin-db. Let me know if you need anything else.

**Comment by NepPure** [comment]
I plan to use GitHub CI to generate all static images of characters and weapons.

https://github.com/NepPure/genshin-card/tree/main/cards/output

> ing...: https://github.com/NepPure/genshin-card/blob/main/cards.js

The free cloudflare and GitHub Pages should be enough. 😁

I added a global CDN to my resource domain, and it should be faster now.

Thank you so much for these resources, they helped me a lot!

**Comment by NepPure** [comment]
Hi, one more question ![5)5NH8})JYI568}K3EGBW)Y](https://user-images.githubusercontent.com/12379907/132537252-2f6ca018-2212-4221-b485-78416d01ccaf.jpg)


![image](https://user-images.githubusercontent.com/12379907/132536927-cad8d230-3764-4635-b45f-e149bf9b56c9.png)

How to match this index number to item json info？

**Comment by theBowja** [comment]
added image names to materials d5f5ee3d8737d005933c4021295011cf7e7f2fc2
```
genshindb.materials('handguard').images.nameicon
// UI_ItemIcon_112044
```

**Comment by theBowja** [comment]
[v3.10.1](https://github.com/theBowja/genshin-db/releases/tag/v3.10.1)
