### ISSUE TITLE
get all weapons/characters data

### ISSUE THREAD

**Issue by Ivan-Da-Dev** [theBowja/genshin-db#43]
Hello! Sorry if I'm bothering you but how would I get ALL characters' and weapons' data? Like for example I want an array of all the characters with their data:
```js
[
  { name: "..." , damage: "..."},
  { name: "..." , damage: "..."},
  { name: "..." , damage: "..."},
]
```

**Comment by theBowja** [comment]
`genshindb.characters('names', { matchCategories: true, verboseCategories: true });`  
`genshindb.weapons('names', { matchCategories: true, verboseCategories: true });`

**Comment by Ivan-Da-Dev** [comment]
Thanks so much! It works! Thanks for creating such a useful npm package and making it open source, and thanks for replying to me so fast, cheers!
