### ISSUE TITLE
monster data

### ISSUE THREAD

**Issue by Ivan-Da-Dev** [theBowja/genshin-db#44]
are there any data about monsters?

**Comment by theBowja** [comment]
Currently there isn't. What kind of data about monsters are you looking for? For example.

I'll look into it.

**Comment by Ivan-Da-Dev** [comment]
Like bosses

**Comment by theBowja** [comment]
[v3.10.3](https://github.com/theBowja/genshin-db/releases/tag/v3.10.3)

Added enemies. If there's anything specific you want me to add, please let me know.
