### ISSUE TITLE
image property for character banner?

### ISSUE THREAD

**Issue by Ivan-Da-Dev** [theBowja/genshin-db#45]
i cant find any image properties that show character images like: https://thumbor.forbes.com/thumbor/960x0/https%3A%2F%2Fspecials-images.forbesimg.com%2Fimageserve%2F603e2e17ca7d53205d3997e2%2FHu-Tao%2F960x0.jpg%3Ffit%3Dscale

**Comment by theBowja** [comment]
I'll make an update later today adding this.

**Comment by theBowja** [comment]
[v3.10.3](https://github.com/theBowja/genshin-db/releases/tag/v3.10.3)

You can access gacha splash images by doing:
```
let imagename = genshindb.characters("hu tao").images.namegachasplash; // UI_Gacha_AvatarImg_Hutao
let url = `https://res.cloudinary.com/genshin/image/upload/2.1/${imagename}.png`;
```
---------------------------

all UI images zip download https://www.mediafire.com/file/l1xw41d0kndsh7k/images2.1.7z/file (1GB)

cloud hosted with 25GB monthly bandwidth https://res.cloudinary.com/genshin/image/upload/2.1/UI_AvatarIcon_Diona_Card.png (just change the file name at the end)

**Comment by Ivan-Da-Dev** [comment]
would it be possible to add the stars to the images?

**Comment by theBowja** [comment]
Sorry. You'll have to do that yourself. [Image for stars.](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADwAAAA8CAMAAAANIilAAAAC3FBMVEUAAABWQABaTB1eUhRtSSRfRxFkTA1jTBdkTBVpSw9mThRiShhvThJkTBFwUBRrTRBvThFsTRNkSxJ2UBJ5TROFUhJnTBRnTBFcTQ9qTRF7ThP/0jN/UhKFUxRzUBSBUxL4wC2mWxKXVxKgWRFuTxJrThWSVxKxYBOIVBOmXRKRVRJ+URSDUxJyUBGSVhN8UhRuThT+yjH5wy7ztyrcjR2uXBKoWRKAUhOucRiRVROXWxR0TxOCURSDUhF1TxF8UBT/zzP+yzH3vizzsijimSHXfBe2XxLHcRSpXRO1XRHAYBGrXBKmXRK4XhGZWRO3YRGxWxGaWRKEURKUWBKAUhKZXBR1UROKVRKPVhJ6UhP/0TP2vSz3wC3ysinYfhjIZBDNdBbJZhHanCPRfhnDZhHIahPVghrKcBTIbBPQgRvFaxPKdBeiWxPFbRSnWhGdWBOlXROGUxOTVhOZVxSRVRSeXBOtXxJ9UhOfWBKJVBK4ZROmZROZXxRsTRSEVRP/1TX/1DT+yzH/zTP4vCv4wC3+zTL+zTLtoSP2uyzurif0uSrtpiXxsyr2wS7wrifrpCPonyLxsyrvuCzprCjjmyHbhxrnoiTqpyXjpCbdkB7ijxzimiLWehbgkR/joybehBnahxvJahO1WxDEZRK4YBKrWxKnXRSyXhHPdxjIdhfKZhKuXxLRlCK3YxS/aRSWVhOyXRO/aROOVhO/gh3JehjFeRi7ZBKfVxKraxeMVRJuTxSaVRH/3jj+yjL/3Tf7xTD/zzP8xjD7yDD1tSrwqSb3uyz6xjDxsSjwsCjtqCXxrSftuS74xTDwsyrikR3ciBzmririlB7PdRbgiRzVchTZhx3bkiDglyDdjh3cjB3IYg/dnSLRix7AXA7RexfKjyLOgxzDZRG7YRLPlCKyXhLGgRrJfhunYBWnXBH/zDP/0jX/1Tb/zjT/zTT/1DX/0DT/1zb/yzP/3Tf/2Dc+5m/kAAAA6XRSTlMABAgMBw4SFRcRGQobHSUfHScbLiM3JSEQLCf6ODMyKt1RSEApI1FPT05EPzs5NDEv6t7Lk1tXQkFAPDYwLSsi+fLZ16iNdm1tbWxnZWFfXFhSSUVEQkE8ODX21crIoJWLioeHhoJ9fXZua2lpaF9cWlpZWExLSUhHR0Q4MjEo/Pv16+bi39XVz8zLysTBwcC6ubKysqunpaSdnZeXlJOTiYV9e3t6eXd1c3Jxa2ZlY19eXFtaWlVKRkQ+O/j19O/t6eTc2dLRzs7Mw8LBvrKwq6CfmpaTj46OjId/f316eXd3cXBkY189Pc3tmqgAAAWASURBVEjHtZZ1e9pQFMZHAkkIAYIXSkuRrrLK2q66ytzdO3d3d3d3d3d3d3d3N5JAZV9gN1kGe0bTwZ7t/Jn7/O773nNz7jkl/l+IRH9N8vFXrBiSgYDEf0GLIVgiRRCpBBYHLC6CYAQjSJLAEBgSBeoZRgmtJSfHoiVQOEDngCVHxw3/sDMtzkQgsDgw01K1Ke5L+5OnX3wFtBQSBWJagmpD7J8nU9Tlg/YQbSDGgTAiz0qPWEEXOMc8iUjPIoF0ANnCFLqoHtMpp5NK6hGlU2D+S4tkiFwTXXdVMON0MsGr6jbWyBGZyG9hXKGzVp1KO0HQ07tbgbQESPvHIsr4hsllWGFWuky9hkDaD+MiEWClakdTa/ckTthZQLfqbo1x4EEyMVgstohAMcAIrsi11S7T3OXkwtW8zF5bbjguhWVilhcVqSiGAClBUFKVG53cNYly8kG16to3OlRPoqBIZBDE7vB7+cFsEaGYmlRozA1Taiwvx/yEmXEPaqREm7MVSgJDkSAJ5+AXWYhVJEil1mTJ1KUPSq5ROREIe6TDKtdIPpKuy7SYtEqSQBGuTL0sgpNaS2ZIs4zGQ631am9fk+h2/hJ0hTXba9eLGmrPaBaSZdGSbJnytAiSgPLLijthHxxxeF+vrWvvXS9PFfwKF1AJs5ev3dpr3+GIwfYTcVmgTAH9816J0SNHDD/YrfPTJfOSEhPKuT2ePc7d5RISk+Yteda526HhI0aOJth754VzRuxcvbjlpLPBFEXlMYzL6RMuhskDi8HjJ7VcvPrAyBxUAv2ApURO2uRCmnL5QL57uBiKLryZpiWkPIyQprT5+T6k4Ab5s9JMHjiIsGQcmkX7C7tbfrJbPLAEN4HqveVmCvxip3aLaGYiwJn5h9IQH51SdWY+44dnusXrurb4cP5lYjOGO8wD93Zp5ce56bAOH+vHONSca15abowpWbPLHJr5k+cKlavXT9UoeWH+ppWlS5WsuWEOnVe85wptqw9IDTVg7Il5mKUNLN1pbjBTrOfK1Qc0Cg3HAQtgL42xdLWOc8u5hD2HrazSZxhgg7ysl07tv+P5DMH7piaurFKnQVk9eJE8rJfWhw6ps7H1GapolqFuv+oZGatSI17WSwfhqtiSO9pVpAVMT3i4pX8To+87ytHgxQ1tUKvTVbdAtiq2qxZZNhzjWZ/uhhtT+2yYJgivq9VglFygbYFGoSrV990VWgC+0KlWI41aoHWIYEwV07er0Jnzyj/qfcxYHNw0pcM5oWzTy5KPFaOMO9JTQIsSgivVtmnkHtgnYdnR9ZZRjNAPNnu3LR4kTABWaxrWrUS7PHVAffuW760UqkXVQSFKpGgYCiLjbbtnuj1/1NgJU6ZcHEcznsaxLUoXjsqKhkFbtvW6RPEnLH/tzv02bdosmlHezX9K6GyNUaBwkbAMUYYcqRpGceejwxa1W79p8+ZN6zu2nnaKdnG99rG1qQIThoe+TQAu8+iJC9turLZnf79+/fb03NKxdYsxFOt7RUQMgMUCcKa9/VhnHnV+Ydsq1epEDmly/HiTIZH7e1ZZV6kCRbmopYN1QrYhKZmd0b7w2/gFHd7XrBPZKHaU0aEyjopt0qB/repdKiXShfOPZhqEYAmhaHbg7oKXu3r3AWhplUGN42q53li21MABvXdtW3rjTUY2iQhkG0aVmqaNB9UvOSw1trRejoEpQCKRohw+bGD9qKONQxTs81X07CbFDdm5ZrM51AhQMMCA+QPMG1JMrneEljWbdRqFWmikYocoTBmuUukNQBUGoxMXAAfqSr1KpTAQKCcsQAehGI5jqBSGWNQ77XDfcW6cEIJF7CwlkcBelAtOnVuQCbEgOJMQTwovCONcCK6U+HfxHSsCDg8UOgOPAAAAAElFTkSuQmCC)

image for elements are in genshindb.elements('pyro')

I don't have the font.
