### ISSUE TITLE
did the banner image get added?

### ISSUE THREAD

**Issue by Ivan-Da-Dev** [theBowja/genshin-db#46]
i just updated the npm package and i saw the enemies data, thank you btw for adding that. Tho did u add the image when u rolled the character? example: https://external-preview.redd.it/GIiM20bfwIimwB0zxndUtzCVsczmECefK5cPqeTsRmM.png?format=pjpg&auto=webp&s=84ec1301828bfe748b9c6aea91056e1d0f922170

**Comment by theBowja** [comment]
please see #45
