### ISSUE TITLE
wrong "Elgaic Rime" domain region

### ISSUE THREAD

**Issue by mciicrw** [theBowja/genshin-db#48]
Elgaic Rime located at peak of dragonspine mountain, so it's _technically_ still in mondstadt, but here it listed it's region as liyue
![2021-09-18-230107_352x64_scrot](https://user-images.githubusercontent.com/20676806/133895065-6da2d8fb-b020-47fa-9762-92b8bc267a73.png)

**Comment by theBowja** [comment]
Huh interesting. Thanks for catching this!

**Comment by mciicrw** [comment]
Glad i can help, i'll close this now
