### ISSUE TITLE
some characters does not have the namegachasplash image property

### ISSUE THREAD

**Issue by Ivan-Da-Dev** [theBowja/genshin-db#49]
why do some characters does not have the namegachasplash property in images?

**Comment by theBowja** [comment]
which characters?

**Comment by Ivan-Da-Dev** [comment]
lumine

**Comment by Ivan-Da-Dev** [comment]
oh i see, understandable

**Comment by theBowja** [comment]
It's because you can't roll lumine or aether from the gacha...

also I couldn't find their portraits in the images I have.
