### ISSUE TITLE
what does {param1:F1P} mean in the talents?

### ISSUE THREAD

**Issue by Ivan-Da-Dev** [theBowja/genshin-db#51]
I dont play genshin but I have looked at the wiki tho i still dont understand what these mean
```js
  {
    "name": "Albedo",
    "combat1": {
      "name": "Normal Attack: Favonius Bladework - Weiss",
      "info": "**Normal Attack**\nPerform up to 5 rapid strikes.\n\n**Charged Attack**\nConsumes a certain amount of Stamina to unleash 2 rapid sword strikes.\n\n**Plunging Attack**\nPlunges from mid-air to strike the ground below, damaging opponents along the path and dealing AoE DMG upon impact.",
      "attributes": {
        "labels": [
          "1-Hit DMG|{param1:F1P}",
          "2-Hit DMG|{param2:F1P}",
          "3-Hit DMG|{param3:F1P}",
          "4-Hit DMG|{param4:F1P}",
          "5-Hit DMG|{param5:F1P}",
          "Charged Attack DMG|{param6:F1P}+{param7:F1P}",
          "Charged Attack Stamina Cost|{param8:F1}",
          "Plunge DMG|{param9:F1P}",
          "Low/High Plunge DMG|{param10:P}/{param11:P}"
        ],
```
this is a sample object of albedo's talents, in combat1's attribute's labels, there are the details about the skills
```js
          "1-Hit DMG|{param1:F1P}",
          "2-Hit DMG|{param2:F1P}",
          "3-Hit DMG|{param3:F1P}",
          "4-Hit DMG|{param4:F1P}",
          "5-Hit DMG|{param5:F1P}",
          "Charged Attack DMG|{param6:F1P}+{param7:F1P}",
          "Charged Attack Stamina Cost|{param8:F1}",
          "Plunge DMG|{param9:F1P}",
          "Low/High Plunge DMG|{param10:P}/{param11:P}"
```
what does `F1P` mean?

**Comment by theBowja** [comment]
F stands for float.
F1 means a number with 1 decimal place.
P stands for percentage.

If you look in the data/stats/talents.json, it has all the values for params.

Then for example, F1P might mean 31.4% or something.

I don't have all the formats documented yet sorry.

**Comment by Ivan-Da-Dev** [comment]
this is pretty confusing but ill try to understand, thanks

**Comment by Ivan-Da-Dev** [comment]
but can i ask what does float mean?

**Comment by Ivan-Da-Dev** [comment]
wait what do u mean by "look into data/stats/talents.json"? i dont see a `data` folder

**Comment by theBowja** [comment]
Floats mean decimal numbers. Any number with decimal numbers in it. Like 4.5 or 2.48842784883.

Also. I meant the attributes.parameters array in the data. That's also where the param numbers are stored.

Level 1 talent is at index 0. For example attributes.parameters.param1[0]

**Comment by Ivan-Da-Dev** [comment]
yes i understand until that part, `attributes.parameters.param1[0]` has the value of `0.36739200353622437` but i still dont understand how would i convert that to 31.4% sorry

**Comment by theBowja** [comment]
I just put out a random number.

0.36739200353622437 with F1P will convert to 36.7%

**Comment by Ivan-Da-Dev** [comment]
OH

**Comment by Ivan-Da-Dev** [comment]
now i understand, thanks

**Comment by Ivan-Da-Dev** [comment]
to confirm, `{param10:P}/{param11:P}` `attributes.parameters.param10[0]`'s value is `1.2783770561218262` and `attributes.parameters.param11[0]`'s value is `1.59676194190979` 

so does that mean the damage is either `123.8` or `159.6`?

**Comment by theBowja** [comment]
No. Pretty sure it is formatted as "128%/160%" in-game.

**Comment by theBowja** [comment]
However if you don't care how the in-game formats this, you don't need to worry too much. Just add however many decimal places you need.

Just remember "P" values need to be multiplied by 100 and add "%" character.

**Comment by Ivan-Da-Dev** [comment]
ah alright, thanks

**Comment by AlexMedinaUma** [comment]
There is an attack type on genshin that is Plunge attack, this type of attack has 2 values of dmg depending of the height, so thats why there are 2 values
