### ISSUE TITLE
Typescript types error

### ISSUE THREAD

**Issue by kaname-png** [theBowja/genshin-db#52]
`"genshin-db": "^3.10.3"`

```ts
node_modules/genshin-db/index.d.ts:99:2 - error TS1036: Statements are not allowed in ambient contexts.

99 };
```

**Comment by theBowja** [comment]
Oops. You can remove the semicolon to get it working temporarily. I will fix this tomorrow. Thanks for catching this! Sorry for the inconvenience.

**Comment by kaname-png** [comment]
I made a pr to fix that https://github.com/theBowja/genshin-db/pull/53
