### ISSUE TITLE
character base damage

### ISSUE THREAD

**Issue by Ivan-Da-Dev** [theBowja/genshin-db#54]
is there data on character's base damage? i am trying to calculate the damage a character will deal on [Genshin's Wiki](https://genshin-impact.fandom.com/wiki/Damage) and it said the formula requires the base damage of the character but i dont see the base damage of the character in the character object

**Comment by theBowja** [comment]
I'm not understanding what you mean by base damage

**Comment by theBowja** [comment]
You can look at [examples](https://github.com/theBowja/genshin-db/blob/main/examples.md).

There's is a stats function on the characters data object that returns the base stats depending on the level.

</details>
<details>
<summary>genshindb.characters('<b>klee'</b>)<b>.stats(90)</b></summary>

```js
{
  level: 90,
  ascension: 6,
  hp: 10286.565419930499,
  attack: 310.93189668962077,
  defense: 614.8434950278315,
  specialized: 0.2879999876022339
}
```
