### ISSUE TITLE
image urls are not working

### ISSUE THREAD

**Issue by Ivan-Da-Dev** [theBowja/genshin-db#55]
All image urls (except the ones on genshin wiki) are not working

**Comment by Ivan-Da-Dev** [comment]
Here is a example: https://res.cloudinary.com/genshin/image/upload/2.1/UI_MonsterIcon_Invoker_Deacon_Electric_01.png

**Comment by theBowja** [comment]
I had to change the url because it had 2.1 and we're no longer on 2.1 update so it would become confusing.

It is now `https://res.cloudinary.com/genshin/image/upload/sprites/${filename}.png`

Sorry for the trouble.

**Comment by Ivan-Da-Dev** [comment]
aight
