### ISSUE TITLE
Get list of all characters

### ISSUE THREAD

**Issue by ahmadkeren** [theBowja/genshin-db#63]
Excuse me, how to get list of all characters?
I don't understand at this text "and 'name' for the list of all characters" in readme.txt

**Comment by theBowja** [comment]
look inside the examples
https://github.com/theBowja/genshin-db/blob/main/examples.md#genshindbcharactersquery-opts

`genshindb.characters('names', { matchCategories: true })` will return a list of all character names.

`'names'` is the query. `matchCategories: true` will let it search for lists and return the list you want.
