### ISSUE TITLE
Total chars and chars in abyss chambers

### ISSUE THREAD

**Issue by ahmadkeren** [theBowja/genshin-db#64]
Excuse me, i want to report if the API return only 8 characters and the abyss API not show all of the chambers detail..
Thanks..
![Screen Shot 2021-11-28 at 20 51 31](https://user-images.githubusercontent.com/49072140/143770747-948f2d16-1904-41f3-babe-c376defc6109.png)

**Comment by theBowja** [comment]
unrelated
