### ISSUE TITLE
Any plans to add TypeScript support?

### ISSUE THREAD

**Issue by meimisaki** [theBowja/genshin-db#7]
It's nice to see such a great database for genshin, well-structured game info, pretty images, and even multi-languages support!

I'm currently developing a genshin build planner(i.e. damage calculator) written in TypeScript, and I would like to use this package as main data source(for those non-numerical properties). So I just wonder if you have any plans to add TypeScript support? Actually I have already written a simple type definition for it, if you don't mind, I might send you a pull request later.

Anyway, thanks for your great work!

**Comment by theBowja** [comment]
I'm unfamiliarity with TypeScript. What would adding TypeScript support entail doing?

**Comment by theBowja** [comment]
I have to say that even though there is support for multiple languages, I don't have any data besides English hah.

**Comment by meimisaki** [comment]
> I'm unfamiliarity with TypeScript. What has to be done for Typescript to be supported?

Well it's quite simple, just need to add a standalone type definition file, and a few lines modification in package.json. You can take a review on my pull request later.

Though the exported TypeScript APIs might be more restrictive than it originally was in JavaScript(mainly due to the fancy overloading), I would try my best to make it generic and robust.

**Comment by meimisaki** [comment]
> I have to say that even though there is support for multiple languages, I don't have any data besides English hah.

Hah don't worry about that, I invited one of my developer friends(who's also playing this game) to help collecting data from miHoYo official wiki for Chinese version. He is planning to write some scripts to automate the process, I really hope there are some open source projects that can help to decrypt and extract raw data from game resources.

I also speak some Japanese, not a native but good enough to understand most game contents. I could assist you with JP version once I finish the basic functions of my build planner.

**Comment by meimisaki** [comment]
Hi, any comments on the [pull request](https://github.com/theBowja/genshin-db/pull/10)? (I noticed new attributes on the weapon object, and may provide you further update later)

**Comment by theBowja** [comment]
Haven't had time to look at it. I'll try get around to it this week.

**Comment by theBowja** [comment]
how do i test myself if the index file works?

**Comment by theBowja** [comment]
supported in v3.5.0
