### ISSUE TITLE
what does "character level-up material" mean?

### ISSUE THREAD

**Issue by oniiichannnn** [theBowja/genshin-db#72]
I thought character level-up material meant that its a material for leveling up your characters but I saw a material
```js
  {
    "name": "Brilliant Diamond Chunk",
    "description": "Character Ascension material.\n\"Welcome to this world.\"",
    "rarity": "4",
    "category": "AVATAR_MATERIAL",
    "materialtype": "Character Level-Up Material",
    "source": [
      "Adventure Rank Reward"
    ],
    "images": {
      "redirect": "https://genshin-impact.fandom.com/wiki/Special:Redirect/file/Item_Brilliant_Diamond_Chunk.png",
      "fandom": "https://static.wikia.nocookie.net/gensin-impact/images/7/74/Item_Brilliant_Diamond_Chunk.png",
      "nameicon": "UI_ItemIcon_104103"
    },
    "url": {
      "fandom": "https://genshin-impact.fandom.com/wiki/Brilliant_Diamond_Chunk"
    }
  }
```
The description says character ascension material but the material type is character level up material

**Comment by theBowja** [comment]
"materialtype": "Character Level-up Material" is what shows up on the item card
![image](https://user-images.githubusercontent.com/12958524/147981624-992e4cc6-5b97-4a51-96f1-af6059d567ca.png)

"category": "AVATAR_MATERIAL" is the broader category of every materials that pertains to characters (talent books, monster mats, etc)

**Comment by oniiichannnn** [comment]
Sorry I dont play genshin but I saw a guide on character exp materials https://gamewith.net/genshin-impact/article/show/22366 and in the guide it shows 3 items that gives ex
![OnPaste 20220104-170601](https://user-images.githubusercontent.com/67128188/148035236-e06a29bb-4d5d-4912-b40f-722cd7ce8433.png)
p

But I don't see them in the database

**Comment by oniiichannnn** [comment]
Actually my bad, turns out it was a problem with my code that caused it not to appear. I see it in the database now
