### ISSUE TITLE
enemies("enemy name").stats() returns undefined?

### ISSUE THREAD

**Issue by oniiichannnn** [theBowja/genshin-db#81]
```js
const gdb = require("genshin-db")

console.log(gdb.enemies("Anemo Samachurl").stats())
```
logs undefined so I tried checking if the enemy exists `console.log(gdb.enemies("Anemo Samachurl"))` and it logged a enemy object. I am using version `genshin-db@4.0.3`

**Comment by theBowja** [comment]
You need to pass in the level of the enemy.

gdb.enemies("Anemo Sama").stats(90)

**Comment by oniiichannnn** [comment]
@theBowja oh, tho did u forget to add the type into the .d.ts file? cuz `stats()` doesn't show up as a suggestion

**Comment by theBowja** [comment]
ah you're right i forgot to add the type. my bad. i'll add that next version
