### ISSUE TITLE
Assets Missing

### ISSUE THREAD

**Issue by ahmadkeren** [theBowja/genshin-db#85]
Excuse me, i want to report some missing image assets:
-----------
UI_AvatarIcon_Yae.png
UI_ItemIcon_101692.png
UI_ItemIcon_101693.png
UI_ItemIcon_113032.png
UI_ItemIcon_113033.png
UI_ItemIcon_113034.png
UI_ItemIcon_200109.png
UI_MonsterIcon_Shougun_Mitakenarukami.png
UI_MonsterIcon_ForlornVessel_Strong_Chargebow_Ice.png
UI_MonsterIcon_ForlornVessel_Strong_Lance_Water.png
UI_MonsterIcon_ForlornVessel_Strong_Warbanner_Fire.png
-----------

**Comment by phrozen** [comment]
I closed the other Issue as this was out of scope, but for example Cinnabar Spindle Icon URL is: https://upload-os-bbs.mihoyo.com/game_record/genshin/equip/UI_EquipIcon_Sword_Opus.png

Which results in a 404, I'm still building my app but will report all the ones I find.

**Comment by theBowja** [comment]
ya idk about that. that's mihoyo's fault for not adding it.

in the meantime u can switch to `https://res.cloudinary.com/genshin/image/upload/sprites/{filename}.png`

**Comment by ahmadkeren** [comment]
Thanks
