### ISSUE TITLE
Incompatible dynamic import with webpack

### ISSUE THREAD

**Issue by meimisaki** [theBowja/genshin-db#9]
I found the dynamic imports used in `src/main.js` makes it hard to integrate with webpack, the build tools wouldn't recognize those non-statically imported JSON files, and left them unbundled, see [tc39 dynamic import proposal](https://github.com/tc39/proposal-dynamic-import).

### the issue:

Failed to load from `src/index` and `src/english`.

```js
function getJSON(path) {
    try {
        // can't infer dependency with a runtime expression
        //             vvvv
        return require(path);
    } catch(e) {
        return undefined;
    }
}
```

### the solution:

Import from a string template, so that webpack understands all files under `src` folder are needed.

```js
function getJSON(path) {
    try {
        return require(`./${path}`);
    } catch(e) {
        return undefined;
    }
}
```

And change to absolute path for each call to `getJSON`:

```js
// optional, repeating './' doesn't make any difference to a path
getJSON(`index/${lang}/${folder}.json`)
```

I'm not sure if this is a decent solution, but at least it works in my use case.

**Comment by theBowja** [comment]
Fixed with commit 59b8c423d140df0940a663e029e5446a46bb7685
