### ISSUE TITLE
Talent Domains at "Taishan Mansion" are at the wrong region

### ISSUE THREAD

**Issue by nlhnam2000** [theBowja/genshin-db#91]
Hi, I found that all the talent domains at __Taishan Mansion__ are at **Mondstadt** instead of **Liyue**. Can you go check it ? 

<img width="834" alt="Ảnh chụp Màn hình 2022-02-27 lúc 00 18 42" src="https://user-images.githubusercontent.com/68092882/155852685-d3347909-46a6-4311-82c9-d663356211a0.png">

**Comment by theBowja** [comment]
good catch.
thanks.

domainentrance is one of the few things i had to manually map

**Comment by theBowja** [comment]
which weapon material

**Comment by nlhnam2000** [comment]
Sorry I can't open my script right now but a few days ago I did a query for weapon material domain for each region and I found that the one which should be located at Liyue is at Monds. My result was ["Mondstadt", "Mondstadt", "Inazuma"] instead of ["Mondstadt", "Liyue", "Inazuma"]

**Comment by Sairei** [comment]
it's for the domain entrance "**Hidden Palace of Lianshan Formula**"

![image](https://user-images.githubusercontent.com/31937866/156944185-9e72d48a-6fd2-46e0-ba9d-ca404d831d41.png)

Problem in the index too

**Comment by theBowja** [comment]
`npm update genshin-db@latest`
