### ISSUE TITLE
Inazuma region's is missing in category.json file

### ISSUE THREAD

**Issue by Sairei** [theBowja/genshin-db#92]
Everything is said in title, but here is a screenshot of the file :

![image](https://user-images.githubusercontent.com/31937866/155863089-7b9005e8-fd4c-4776-9376-821560427eee.png)

**Comment by theBowja** [comment]
Sorry I don't update the categories file anymore. I should remove it or update it.

In the meantime, all the category values are actually updated in the index files.

https://github.com/theBowja/genshin-db/blob/main/src/data/index/English/characters.json

See under the "properties" property.

**Comment by Sairei** [comment]
OK, thanks :)

Then I think I can close this issue
