### ISSUE TITLE
Unable to use "genshindb-none.js"

### ISSUE THREAD

**Issue by misemi1** [theBowja/genshin-db#93]
I tried to install genshin-db to my nuxt project according to [this page](https://github.com/theBowja/genshin-db/tree/main/dist) ("using the webpack dist in Node") but when I run `npm run dev` I got this error `Cannot assign to read only property 'exports' of object '#<Object>'` .

```javascript
// test.js

const genshindb = require("../genshin-db/dist/genshindb-none.js")  // <- here i got the error

// English
require("../genshin-db/dist/data/scripts/english-artifacts.js")(genshindb)
require("../genshin-db/dist/data/scripts/english-characters.js")(genshindb)
require("../genshin-db/dist/data/scripts/english-constellations.js")(genshindb)
require("../genshin-db/dist/data/scripts/english-talents.js")(genshindb)
require("../genshin-db/dist/data/scripts/english-weapons.js")(genshindb)

// Japanese
require("../genshin-db/dist/data/scripts/japanese-artifacts.js")(genshindb)
require("../genshin-db/dist/data/scripts/japanese-characters.js")(genshindb)
require("../genshin-db/dist/data/scripts/japanese-constellations.js")(genshindb)
require("../genshin-db/dist/data/scripts/japanese-talents.js")(genshindb)
require("../genshin-db/dist/data/scripts/japanese-weapons.js")(genshindb)

console.log(genshindb.characters("hu tao"))

module.exports = genshindb
```

I'm using nuxt and this error doesn't occur with "node test.js". How can I fix it?
This error doesn't occur when I install genshin-db with "npm install genshin-db".

**Comment by theBowja** [comment]
Do you need to export 'genshindb'? It is already it's own module.

In subsequent script, you can just grab genshindb with `const genshindb = require("../genshin-db/dist/genshindb-none.js")` again. And since it's javascript, you don't need to load the data again.

**Comment by theBowja** [comment]
According to the error, you cannot mix `import` with `require`. Try find the places you are mixing them.
https://stackoverflow.com/questions/42449999/webpack-import-module-exports-in-the-same-module-caused-error

**Comment by misemi1** [comment]
This error occurs inside `genshindb-none.js` so I can't find the places mixing `import` and `require`.
Other `require` doesn't show this error.

![image](https://user-images.githubusercontent.com/42956818/157486879-207cd43f-57bb-4eba-a6e8-30f5ce72d63f.png)

**Comment by misemi1** [comment]
I decided to use the local genshin-db package built with "npm run build English Japanese".
I replaced all "module.exports/require" in the genshin-db/src folder with "export/import" and now it works without error. Thanks!
